baseURL = "http://localhost/slides/"
publishDir = "development"
buildDrafts = true
buildFuture = true
title = "Slide decks — Heavy Watal"
disableKinds = ["RSS", "sitemap"]
ignoreFiles = ["\\.R$", "\\.Rmd$", "\\.csv$"]
noTimes = true
pygmentsUseClasses = true
pygmentsCodefences = true
googleAnalytics = "UA-41178626-2"

[author]
name = "Watal M. Iwasaki"
twitter = "@heavywatal"

[markup.goldmark.renderer]
unsafe = true

[params]
og_image = "https://avatars.githubusercontent.com/heavywatal"

[[module.imports]]
path = "github.com/heavywatal/hugo-theme-reveal"
