baseURL = "http://localhost/slides/"
publishDir = "development"
buildDrafts = true
buildFuture = true
title = "Slide decks — Heavy Watal"
disableKinds = ["RSS", "sitemap"]
noTimes = true
googleAnalytics = "G-V60H2JH0G6"

[author]
name = "Watal M. Iwasaki"
twitter = "@heavywatal"

[params]
og_image = "https://avatars.githubusercontent.com/heavywatal"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[module]
workspace = "hugo.work"
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-reveal"
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['**.qmd', '**.Rmd', '**.R', '**.csv', '*/cache', '*/stan']
