baseURL = "http://localhost/slides/"
publishDir = "development"
buildDrafts = true
buildFuture = true
title = "Slide decks — Heavy Watal"
defaultContentLanguage = "ja"
disableKinds = ["RSS", "sitemap"]
noTimes = true

[params]
og_image = "https://avatars.githubusercontent.com/heavywatal"

[params.author]
name = "Watal M. Iwasaki"

[params.social]
twitter = "@heavywatal"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
strikethrough = false

[markup.highlight]
noClasses = false

[module]
workspace = "hugo.work"
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-reveal"
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['*/*.Rmd']
