baseURL = "http://localhost/slides/"
publishDir = "development"
buildDrafts = true
buildFuture = true
title = "Slide decks — Heavy Watal"
defaultContentLanguage = ""
disableKinds = ["RSS", "sitemap"]
noTimes = true

[author]
name = "Watal M. Iwasaki"
twitter = "@heavywatal"

[params]
og_image = "https://avatars.githubusercontent.com/heavywatal"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[module]
workspace = "hugo.work"
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-reveal"
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['*/*.Rmd']
