```{r, setup-common}
#| file: "setup.R"
#| echo: false
#| results: "asis"
```
```{r, setup-local}
#| include: false
#| cache: false
```

---
## 最終日のお品書き

- 13:00 ここまでのおさらい、レポートについて、など
- 13:10 **グループ雑談 40分**
- 13:50 4日目課題1の(**発表5分 + 質疑応答3分**) x 8班
- 15:00 休憩
- 15:10 **グループ雑談 40分**
- 15:50 4日目課題2の(**発表5分 + 質疑応答3分**) x 8班
- 17:00 講評: 牧野能士教授
- 解散、質疑応答


---
## Lightning Talk (LT)

発表者として
: 短い持ち時間で言いたいことを言う。
: うまく情報を絞って整理する必要がある。

聴衆として
: 自分が理解していない部分を探す。
: 必ず**1つは質問するつもり**で聞く。できれば実際にする。

<br>
<hr>

<p><aside style="color: #999999;">受講生から質問が出なければTAがする。</aside></p>


---
## 4日目の課題

<iframe width="400" height="300" src="./7-distribution.html#/1"></iframe>

<iframe width="400" height="300" src="./8-glm.html#/1"></iframe>


---
## 🔰 レポート


---
## この実習でやったこと

✅ 生物学研究にはデータとモデルが必須だと認識

✅ 再現可能な解析を楽にやりたい気持ちになる

✅ 必要な方法を調べ、実践する力をつける

✅ データ解析の基本に触れる

<br>
個々の方法は覚えなくても大丈夫！<br>
<strong>忘れては調べ、を何度も繰り返しながら染み込ませていこう。</strong>

今はまだ完全に飲み込めなくても、
**班員と協力して**レポートを提出しよう。

<a href="." class="readmore">
目次に戻る
</a>
